config/routes.rb
TeamTaskProto::Application.routes.draw do
  root to: 'tasks#index'

  resources :tasks, only: [:index, :new, :create] do
    member do
      post 'has_been_completed'
    end
    resources :comments, only: [:create]
  end

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :skills, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :user_id, :post_id

  validates_presence_of :body

  belongs_to :user
  belongs_to :task
end

app/models/obligation.rb
class Obligation < ActiveRecord::Base
  attr_accessible :user_id, :task_id, :date_completed

  belongs_to :user
  belongs_to :task
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description

  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :tasks
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name

  has_many :skill_tasks
  has_many :tasks, through: :skill_tasks

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/skill_task.rb
class SkillTask < ActiveRecord::Base
  belongs_to :skill 
  belongs_to :task 
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :project_id, :skill_ids, :user_ids, :description, :weight, :due_date

  has_many :user_tasks
  has_many :users, through: :user_tasks

  has_many :skill_tasks
  has_many :skills, through: :skill_tasks

  has_many :comments

  has_many :obligations

  belongs_to :project

  validates_presence_of :description

  def belongs_to_specific_project?
    project != nil 
  end
end

app/models/try_mailer.rb
class TryMailer < ActiveRecord::Base
  def self.maily
    AppMailer.try_send(User.first).deliver
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password

  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  has_many :comments

  has_many :obligations

  validates_presence_of :email, :name
  validates_uniqueness_of :email
  
  has_secure_password

  # need to test this
  def tasks_assigned_today
    todays_tasks = []
    tasks.each do |task|
      todays_tasks << task if task.due_date == Date.today
    end
    todays_tasks
  end

  # need to test
  def tasks_completed_today
    Obligation.where(user_id: self.id, date_completed: Date.today).map {|obligation| obligation.task }
  end
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  belongs_to :user 
  belongs_to :task 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_user
    redirect_to login_path unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def team_users
    User.all.select {|user| user.id != current_user.id}
  end

  helper_method :current_user, :team_users, :require_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new
    redirect_to root_path if current_user
  end

  def create 
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'You are signed in'
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy 
    session[:user_id] = nil
    redirect_to root_path, notice: "You are signed out"
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(params[:skill]) 
    if @skill.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController 
  before_filter :require_user

  def index
    @tasks = Task.all
    @obligations = Obligation.where(user_id: current_user.id) 
  end

  def new
    @task = Task.new
  end

  def create 
    @task = Task.new(params[:task])
    if @task.save
      @task.users.each do |user|
        Obligation.create(user_id: user.id, task_id: @task.id, date_completed: nil)
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def has_been_completed
    @task = Task.find(params[:id])
    @obligation = Obligation.where(user_id: current_user.id, task_id: @task.id).first
    @obligation.update_attributes(date_completed: Date.today)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_filter :require_user, only: [:show]

  def show 
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      AppMailer.send_welcome_email(@user).deliver
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar ">
  <div class="navbar-inner">
    <%= link_to "Home", root_path, class: 'brand' %>
    <ul class="nav">
      <li class=""><%= link_to "#{current_user.name}", user_path(current_user) %></li>
      <li><%= link_to "#{team_users.first.name}", user_path(team_users.first) %></li>
      <li><%= link_to "#{team_users.last.name}", user_path(team_users.last) %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamTaskProto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>


<%= yield %>

</div>
</body>
</html>

app/views/skills/new.html.erb
<%= semantic_form_for @skill do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <p>Description: <%= task.description %> </p>
  <p>Weight: <%= task.weight %> </p>
  <p>Due Date: <%= task.due_date %> </p>
  <p>
    Skills:
    <% task.skills.each do |skill| %>
    <span><%= skill.name %>
    <% end %>
  </p>
  <p>
    Users: 
    <% task.users.each do |user| %>
      <span><%= user.name %></span>
    <% end %>
  </p>
  <% if task.belongs_to_specific_project? %>
    <p>Project: <% task.project.name %></p>
  <% else %>
    <p>Project: None</p>
  <% end %>
  <p>
    <% if Obligation.where(user_id: current_user.id, task_id: task.id).first.nil?%>

    <% else %>
      <% if Obligation.where(user_id: current_user.id, task_id: task.id).first.date_completed.nil? %>
        <%= link_to "DONE!", has_been_completed_task_path(task), method: 'post' %>
      <% else %>
        <%= "Completed on: #{Obligation.where(user_id: current_user.id, task_id: task.id).first.date_completed}" %>
      <% end %>
    <% end %>
  </p>
  <br>
<% end %>
<%= link_to "New Task", new_task_path %>

app/views/tasks/new.html.erb
<%= semantic_form_for @task do |f| %>
  <%= f.input :description %>
  <%= f.input :weight %>
  <%= f.input :skills %>
  <%= f.input :due_date %>
  <%= f.input :users %>
  <%= f.input :project %>
  <%= f.action :submit %>
<% end %>

app/views/users/new.html.erb
<%= semantic_form_for @user do |f| %>
  <%= f.input :email, label: "Email Address" %>
  <%= f.input :password %>
  <%= f.input :name, label: "Full Name" %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<h3><%= @user.email %></h3>